#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=32:mem=124gb

module load anaconda3/personal
module load cuda/11.0.1
source activate tf_gnn

export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1

cd $PBS_O_WORKDIR
python train.py RGCN QM9 --run-test --model-param-overrides "{\"random_seed\": 1}" --task-param-overrides "{\"task_ids\": [0], \"preprocess_with_sdrf\": \"True\"}"
